getQuestions:
  handler: functions/questions/questions.get
  events:
    - httpApi:
        path: /v1/questions
        method: get

postQuestions:
  handler: functions/questions/questions.post
  events:
    - httpApi:
        path: /v1/questions
        method: post
