service: sls
frameworkVersion: '3'

provider:
  name: aws
  region: ap-southeast-2
  runtime: python3.9

functions:
  hello:
    handler: handler.hellos
    events:
      - httpApi:
          path: /
          method: get
