service: web-api
frameworkVersion: '3'

provider:
  name: aws
  region: ap-southeast-2
  runtime: python3.9
  layers:
    - !Ref CommonLambdaLayer

layers:
  common:
    path: common
    compatibleRuntimes:
      - python3.9
    description: 'Common utils shared across functions'

functions:
  - ${file(./functions/exams/serverless.yaml)}
  - ${file(./functions/questions/serverless.yaml)}

resources:
  Resources:
    - ${file(./tables/exams.yaml)}
    - ${file(./tables/exam-questions.yaml)}