service: web-api
projectDir: '../../../'
frameworkVersion: '3'

provider:
  name: aws
  region: ap-southeast-2
  runtime: python3.9

functions:
  - ${file(./functions/exams/serverless.yaml)}
  - ${file(./functions/questions/serverless.yaml)}
