name: Prod - deploy website

on:
  push:
    branches:
      - "main"
    paths:
      - "web/**"

concurrency:
  group: terraform_web_prod

jobs:
  deploy:
    name: Deploy web (prod)
    runs-on: ubuntu-latest
    env:
      REACT_APP_GS_API_ENDPOINT: ${{ secrets.PROD_REACT_APP_GS_API_ENDPOINT }}
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_DEPLOYER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_DEPLOYER_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      # TODO: run tests
      # - name: Run tests
      #   run: ???

      - name: Build
        run: CI=false && yarn run build

      - name: Deploy
        if: success()
        run: aws s3 sync ./build s3://prod.groundschool.co.nz/ --acl public-read
